In [1]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
data = pd.read_csv('2020.csv')
data

/var/folders/wc/x5gp3bsd6vqbq64wlf8ybk3r0000gn/T/ipykernel_51527/1973062257.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('2020.csv')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city
0,38585,Charming Victorian home - twin beds + breakfast,165529,Evelyne,NaN,28804,35.651460,-82.627920,Private room,60,1,138,16/02/20,1.14,1,0,Asheville
1,80905,French Chic Loft,427027,Celeste,NaN,28801,35.597790,-82.555400,Entire home/apt,470,1,114,07/09/20,1.03,11,288,Asheville
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,Lisa,NaN,28801,35.606700,-82.555630,Entire home/apt,75,30,89,30/11/19,0.81,2,298,Asheville
3,155305,Cottage! BonPaul + Sharky's Hostel,746673,BonPaul,NaN,28806,35.578640,-82.595780,Entire home/apt,90,1,267,22/09/20,2.39,5,0,Asheville
4,160594,Historic Grove Park,769252,Elizabeth,NaN,28801,35.614420,-82.541270,Private room,125,30,58,19/10/15,0.52,1,0,Asheville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226025,45506143,"DC Hidden In Plain ""Site""",25973146,Marci,NaN,"Downtown, Chinatown, Penn Quarters, Mount Vern...",38.903880,-77.029730,Entire home/apt,104,1,0,NaN,NaN,2,99,Washington D.C.
226026,45511428,DC 3 BR w/ screen porch 3 blck to metro w/ par...,231133074,Thomas,NaN,"Brookland, Brentwood, Langdon",38.920820,-76.990980,Entire home/apt,151,2,0,NaN,NaN,1,300,Washington D.C.
226027,45514685,Charming Penthouse Apt w/ Rooftop Terrace in L...,33758935,Bassem,NaN,"Shaw, Logan Circle",38.911170,-77.033540,Entire home/apt,240,2,0,NaN,NaN,1,173,Washington D.C.
226028,45516412,Adams Morgan/Nat'l Zoo 1 BR Apt #32,23193071,Michael,NaN,"Kalorama Heights, Adams Morgan, Lanier Heights",38.926630,-77.044360,Entire home/apt,60,21,0,NaN,NaN,5,362,Washington D.C.
226029,45517735,Beautiful large one-bedroom w/ washer and dryer,17789858,Adam,NaN,"Edgewood, Bloomingdale, Truxton Circle, Eckington",38.911569,-77.009431,Entire home/apt,79,7,0,NaN,NaN,2,62,Washington D.C.

In [5]:
cities = data['city'].unique()

array(['Asheville', 'Austin', 'Boston', 'Broward County', 'Cambridge',
       'Chicago', 'Clark County', 'Columbus', 'Denver', 'Hawaii',
       'Jersey City', 'Los Angeles', 'Nashville', 'New Orleans',
       'New York City', 'Oakland', 'Pacific Grove', 'Portland',
       'Rhode Island', 'Salem', 'San Clara Country', 'San Diego',
       'San Francisco', 'San Mateo County', 'Santa Cruz County',
       'Seattle', 'Twin Cities MSA', 'Washington D.C.'], dtype=object)

In [6]:
state_mapping = {
    'Asheville': 'North Carolina',
    'Austin': 'Texas',
    'Boston': 'Massachusetts',
    'Broward County': 'Florida',
    'Cambridge': 'Massachusetts',
    'Chicago': 'Illinois',
    'Clark County': 'Nevada',
    'Columbus': 'Ohio',
    'Denver': 'Colorado',
    'Hawaii': 'Hawaii',
    'Jersey City': 'New Jersey',
    'Los Angeles': 'California',
    'Nashville': 'Tennessee',
    'New Orleans': 'Louisiana',
    'New York City': 'New York',
    'Oakland': 'California',
    'Pacific Grove': 'California',
    'Portland': 'Oregon',
    'Rhode Island': 'Rhode Island',
    'Salem': 'Oregon',
    'San Clara Country': 'California',
    'San Diego': 'California',
    'San Francisco': 'California',
    'San Mateo County': 'California',
    'Santa Cruz County': 'California',
    'Seattle': 'Washington',
    'Twin Cities MSA': 'Minnesota',
    'Washington D.C.': 'District of Columbia'
}

In [8]:
data['state'] = data['city'].map(state_mapping)

In [9]:
data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,state
0,38585,Charming Victorian home - twin beds + breakfast,165529,Evelyne,NaN,28804,35.651460,-82.627920,Private room,60,1,138,16/02/20,1.14,1,0,Asheville,North Carolina
1,80905,French Chic Loft,427027,Celeste,NaN,28801,35.597790,-82.555400,Entire home/apt,470,1,114,07/09/20,1.03,11,288,Asheville,North Carolina
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,Lisa,NaN,28801,35.606700,-82.555630,Entire home/apt,75,30,89,30/11/19,0.81,2,298,Asheville,North Carolina
3,155305,Cottage! BonPaul + Sharky's Hostel,746673,BonPaul,NaN,28806,35.578640,-82.595780,Entire home/apt,90,1,267,22/09/20,2.39,5,0,Asheville,North Carolina
4,160594,Historic Grove Park,769252,Elizabeth,NaN,28801,35.614420,-82.541270,Private room,125,30,58,19/10/15,0.52,1,0,Asheville,North Carolina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226025,45506143,"DC Hidden In Plain ""Site""",25973146,Marci,NaN,"Downtown, Chinatown, Penn Quarters, Mount Vern...",38.903880,-77.029730,Entire home/apt,104,1,0,NaN,NaN,2,99,Washington D.C.,District of Columbia
226026,45511428,DC 3 BR w/ screen porch 3 blck to metro w/ par...,231133074,Thomas,NaN,"Brookland, Brentwood, Langdon",38.920820,-76.990980,Entire home/apt,151,2,0,NaN,NaN,1,300,Washington D.C.,District of Columbia
226027,45514685,Charming Penthouse Apt w/ Rooftop Terrace in L...,33758935,Bassem,NaN,"Shaw, Logan Circle",38.911170,-77.033540,Entire home/apt,240,2,0,NaN,NaN,1,173,Washington D.C.,District of Columbia
226028,45516412,Adams Morgan/Nat'l Zoo 1 BR Apt #32,23193071,Michael,NaN,"Kalorama Heights, Adams Morgan, Lanier Heights",38.926630,-77.044360,Entire home/apt,60,21,0,NaN,NaN,5,362,Washington D.C.,District of Columbia
226029,45517735,Beautiful large one-bedroom w/ washer and dryer,17789858,Adam,NaN,"Edgewood, Bloomingdale, Truxton Circle, Eckington",38.911569,-77.009431,Entire home/apt,79,7,0,NaN,NaN,2,62,Washington D.C.,District of Columbia

In [11]:
hosts_multiple_states = data.groupby('host_id')['state'].nunique().reset_index()
hosts_multiple_states

          host_id  state
0              23      1
1             470      1
2             521      1
3             615      1
4             666      1
...           ...    ...
130420  367415444      1
130421  367565136      1
130422  367730375      1
130423  367907062      1
130424  367917574      1

[130425 rows x 2 columns]

In [26]:
hosts_multiple_states = hosts_multiple_states[hosts_multiple_states['state'] > 2]
hosts_multiple_states

          host_id  state
780         85132      5
926        103427      5
3684       602654      4
6875      1381289      5
16078     4140161      4
18356     4962900      6
19988     5634859      4
26057     8534462      5
27727     9419684      5
29949    10595328      5
30665    10981379      7
31836    11697746      5
32636    12243051      5
37627    16222167      4
45156    22541573      4
46684    23853826      4
47015    24126726      7
47906    24831061      6
49693    26521212      4
50167    27042710      4
53110    30283594      6
53522    30787515      8
53638    30922508      4
53853    31214940      8
60833    39880373      5
66077    47475013      7
66415    48005494      6
69714    52651623      4
72856    58385754      5
74717    62563056      4
78286    70722023      4
84497    88566861      7
86612    95459395      5
87940   100238132      6
88030   100605868      6
90093   107434423      6
90810   109904033      6
91847   114353388      6
97364   136676366      6
98903   143519492      4
99597   146389910      7
102839  159355723      4
103862  163251048      4
106352  174792040      6
109707  194953121      9
111317  205315783      5
115068  229095817      5
116161  236664052      5
117450  246225955      6
119897  262977661      4
119939  263243483      5
119981  263502162      5
120384  266065811      4
125054  303719667      4
125160  304341894      6
128884  341289896      4
129033  342643084      6
129657  349823908      5

In [27]:
result = pd.merge(data, hosts_multiple_states, on='host_id')
result

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,state_x,state_y
0,20306649,Luxe South Austin Home Near Lady Bird Lake,143519492,TurnKey Vacation Rentals,NaN,78741,30.24571,-97.73400,Entire home/apt,199,2,30,19/07/20,0.63,13,0,Austin,Texas,4
1,20322030,"Stylish Home: Chef's Kitchen, Fenced Yard & Patio",143519492,TurnKey Vacation Rentals,NaN,78702,30.25926,-97.72887,Entire home/apt,236,2,30,13/09/20,0.57,13,0,Austin,Texas,4
2,20322033,Bright & Modern East Austin Home - Walk Everyw...,143519492,TurnKey Vacation Rentals,NaN,78702,30.26008,-97.72891,Entire home/apt,105,2,30,08/03/20,0.63,13,0,Austin,Texas,4
3,20322156,Gorgeous Home - Walk to the Best of South Austin,143519492,TurnKey Vacation Rentals,NaN,78704,30.23533,-97.76749,Entire home/apt,142,2,20,09/03/20,0.46,13,0,Austin,Texas,4
4,20322218,3BR Colorful SoFi House,143519492,TurnKey Vacation Rentals,NaN,78704,30.24638,-97.75903,Entire home/apt,237,2,11,25/08/20,0.33,13,345,Austin,Texas,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7469,30822611,Elegant One Bed on South 4th Street,4962900,Stay Alfred,NaN,Hennepin,44.97713,-93.26203,Entire home/apt,999,2,2,27/05/19,0.12,13,364,Twin Cities MSA,Minnesota,6
7470,30822613,Fabulous One Bed on South 4th Street,4962900,Stay Alfred,NaN,Hennepin,44.97572,-93.26282,Entire home/apt,999,2,1,02/02/20,0.19,13,364,Twin Cities MSA,Minnesota,6
7471,32020483,Bold Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97896,-93.26853,Entire home/apt,999,2,2,12/01/20,0.31,13,362,Twin Cities MSA,Minnesota,6
7472,32314165,Cozy Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97883,-93.26978,Entire home/apt,999,2,8,15/03/20,0.57,13,357,Twin Cities MSA,Minnesota,6
7473,32314170,Dreamy Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97834,-93.26870,Entire home/apt,999,2,7,08/12/19,0.49,13,361,Twin Cities MSA,Minnesota,6

In [65]:
id_dict = result.groupby('host_id')['id'].apply(list).to_dict()

result['housing_id_list'] = result['host_id'].map(id_dict)

In [69]:
result = result.rename(columns={"state_x": "state"})

In [71]:
result

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,state,state_y,housing_id_list
0,20306649,Luxe South Austin Home Near Lady Bird Lake,143519492,TurnKey Vacation Rentals,NaN,78741,30.24571,-97.73400,Entire home/apt,199,2,30,19/07/20,0.63,13,0,Austin,Texas,4,"[20306649, 20322030, 20322033, 20322156, 20322..."
1,20322030,"Stylish Home: Chef's Kitchen, Fenced Yard & Patio",143519492,TurnKey Vacation Rentals,NaN,78702,30.25926,-97.72887,Entire home/apt,236,2,30,13/09/20,0.57,13,0,Austin,Texas,4,"[20306649, 20322030, 20322033, 20322156, 20322..."
2,20322033,Bright & Modern East Austin Home - Walk Everyw...,143519492,TurnKey Vacation Rentals,NaN,78702,30.26008,-97.72891,Entire home/apt,105,2,30,08/03/20,0.63,13,0,Austin,Texas,4,"[20306649, 20322030, 20322033, 20322156, 20322..."
3,20322156,Gorgeous Home - Walk to the Best of South Austin,143519492,TurnKey Vacation Rentals,NaN,78704,30.23533,-97.76749,Entire home/apt,142,2,20,09/03/20,0.46,13,0,Austin,Texas,4,"[20306649, 20322030, 20322033, 20322156, 20322..."
4,20322218,3BR Colorful SoFi House,143519492,TurnKey Vacation Rentals,NaN,78704,30.24638,-97.75903,Entire home/apt,237,2,11,25/08/20,0.33,13,345,Austin,Texas,4,"[20306649, 20322030, 20322033, 20322156, 20322..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7469,30822611,Elegant One Bed on South 4th Street,4962900,Stay Alfred,NaN,Hennepin,44.97713,-93.26203,Entire home/apt,999,2,2,27/05/19,0.12,13,364,Twin Cities MSA,Minnesota,6,"[28664553, 28664607, 28664619, 28664653, 28664..."
7470,30822613,Fabulous One Bed on South 4th Street,4962900,Stay Alfred,NaN,Hennepin,44.97572,-93.26282,Entire home/apt,999,2,1,02/02/20,0.19,13,364,Twin Cities MSA,Minnesota,6,"[28664553, 28664607, 28664619, 28664653, 28664..."
7471,32020483,Bold Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97896,-93.26853,Entire home/apt,999,2,2,12/01/20,0.31,13,362,Twin Cities MSA,Minnesota,6,"[28664553, 28664607, 28664619, 28664653, 28664..."
7472,32314165,Cozy Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97883,-93.26978,Entire home/apt,999,2,8,15/03/20,0.57,13,357,Twin Cities MSA,Minnesota,6,"[28664553, 28664607, 28664619, 28664653, 28664..."
7473,32314170,Dreamy Two Bed at Soo Line,4962900,Stay Alfred,NaN,Hennepin,44.97834,-93.26870,Entire home/apt,999,2,7,08/12/19,0.49,13,361,Twin Cities MSA,Minnesota,6,"[28664553, 28664607, 28664619, 28664653, 28664..."

In [70]:
result.to_csv('project.csv', index=False)

In [47]:
states = set(result['state_x'])
states

{'California',
 'Colorado',
 'District of Columbia',
 'Florida',
 'Hawaii',
 'Illinois',
 'Louisiana',
 'Massachusetts',
 'Minnesota',
 'Nevada',
 'New Jersey',
 'New York',
 'Ohio',
 'Oregon',
 'Rhode Island',
 'Tennessee',
 'Texas',
 'Washington'}

In [33]:
host_ids = result['host_id'].unique()
host_ids

array([143519492,  10981379,  47475013,  70722023, 100605868,    103427,
        31214940,    602654, 159355723,  26521212,  24126726,   1381289,
       109904033,  30787515,   5634859, 194953121, 246225955, 146389910,
        88566861,  10595328, 263502162, 303719667, 262977661, 263243483,
        11697746, 341289896, 349823908, 304341894, 205315783,  58385754,
         9419684,  30283594,  22541573,  12243051,  95459395, 163251048,
       107434423,  48005494,   8534462,   4140161,  52651623,     85132,
        27042710,  62563056,  23853826,  16222167,  30922508,  24831061,
       100238132, 236664052, 174792040, 266065811, 229095817, 342643084,
       136676366,  39880373, 114353388,   4962900])

In [56]:
def create_state_dict(row_idx):
    target_row = result[result['host_id'] == row_idx]
    states_set = set(target_row['state_x'])
    state_dict = {state: 1 if state in states_set else 0 for state in states}
 # Add the 'xxxx' key with a value of 0
    return state_dict


row_idx = 143519492
state_dict = create_state_dict(row_idx)
print(state_dict)

{'District of Columbia': 0, 'Ohio': 0, 'Massachusetts': 0, 'Hawaii': 0, 'Florida': 0, 'Louisiana': 0, 'Oregon': 0, 'New York': 0, 'Rhode Island': 0, 'Minnesota': 0, 'Texas': 1, 'Washington': 1, 'Tennessee': 1, 'Nevada': 0, 'New Jersey': 0, 'Illinois': 0, 'Colorado': 0, 'California': 1}

In [57]:
store = []

In [58]:
for i in host_ids:
    store.append(create_state_dict(i))

In [59]:
store

[{'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 1,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 1,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 1,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 1,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 1,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 1,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 1,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 1,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 1,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 1,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 1,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 0},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 1,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 1,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 1,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 0,
  'New York': 1,
  'Rhode Island': 1,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 0,
  'Tennessee': 1,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 0,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 0,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 1,
  'Oregon': 0,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 0,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 1,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 1,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 1,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 1,
  'California': 1},
 {'District of Columbia': 0,
  'Ohio': 1,
  'Massachusetts': 0,
  'Hawaii': 0,
  'Florida': 0,
  'Louisiana': 0,
  'Oregon': 1,
  'New York': 0,
  'Rhode Island': 0,
  'Minnesota': 1,
  'Texas': 0,
  'Washington': 1,
  'Tennessee': 0,
  'Nevada': 0,
  'New Jersey': 0,
  'Illinois': 0,
  'Colorado': 1,
  'California': 1}]

In [60]:
def combine_dictionaries(dictionaries):
    combined_dict = {}
    for dictionary in dictionaries:
        for key, value in dictionary.items():
            combined_dict[key] = combined_dict.get(key, 0) + value
    return combined_dict

In [61]:
combine_dictionaries(store)

{'District of Columbia': 7,
 'Ohio': 3,
 'Massachusetts': 9,
 'Hawaii': 25,
 'Florida': 30,
 'Louisiana': 17,
 'Oregon': 9,
 'New York': 29,
 'Rhode Island': 6,
 'Minnesota': 5,
 'Texas': 30,
 'Washington': 19,
 'Tennessee': 18,
 'Nevada': 32,
 'New Jersey': 8,
 'Illinois': 7,
 'Colorado': 7,
 'California': 44}